---
title: "Weekly Patient Report"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(echarts4r)
library(ggplot2)
library(ggthemes)
library(DT)

# Example layouts: https://pkgs.rstudio.com/flexdashboard/articles/examples.html
# Change the theme using bootswatch: https://bootswatch.com/default/

# set wd in a new manner for these types of documents
knitr::opts_knit$set(root.dir = '~/Desktop/Hult_Visualizing_Analyzing_Data_with_R/personalFiles')
# setwd("~/Desktop/Hult_Visualizing_Analyzing_Data_with_R/personalFiles")

# Identify the file in the directory
searchPattern <- 'Wk4'
pth <- "~/Desktop/Hult_Visualizing_Analyzing_Data_with_R/Lessons/C_Report_Automation/data"
pth <- list.files(path = pth, pattern = searchPattern, full.names = T)
pth <- pth[grep('*.csv', pth)]
df  <- read.csv(pth)
```

Row 
-----------------------------------------------------------------------

### Report Date

```{r date}
valueBox(Sys.Date(), 
         icon = "fa-calendar-check-o", #http://fontawesome.io/icon/calendar-check-o/
         color = "#bada55")

```

Row
-----------------------------------------------------------------------

### Age Distribution

```{r histogram, message=FALSE}
ggplot(data = df, aes(age)) + geom_density(color = 'red') + theme_gdocs()
```

Row {data-height=350}
-------------------------------------
   
### Relationships Age Num Meds

```{r scatter1, message=FALSE}
df %>%
  e_charts(age) %>%
  e_scatter(num_medications, bind = patient_id, symbol_size = 10) %>%
  e_tooltip(formatter = htmlwidgets::JS(
    '
    function(params){
      return("patient_id: " + params.data.name + "<br/>" + "age: " + params.data.value[0] + "<br/>" + "num_medications: " + params.data.value[1]);
    }
    '
   )) %>%
  e_x_axis(age, name = 'age') %>%
  e_y_axis(num_medications, name = 'number meds') %>%
  e_toolbox_feature(feature = c("saveAsImage", "dataZoom", "dataView")) 
```   
    
### Relationships Age Num Procedures

```{r scatter2, message=FALSE}
df %>%
  e_charts(age) %>%
  e_scatter(num_lab_procedures, bind = patient_id,symbol_size = 10) %>%
  e_tooltip(formatter = htmlwidgets::JS(
    '
    function(params){
      return("patient_id: " + params.data.name + "<br/>" + "age: " + params.data.value[0] + "<br/>" + "num_lab_procedures: " + params.data.value[1]);
    }
    '
  )) %>%
  e_x_axis(age, name = 'age') %>%
  e_y_axis(num_medications, name = 'number meds') %>%
  e_toolbox_feature(feature = c("saveAsImage", "dataZoom", "dataView")) 
```

Row 
-------------------------------------

### basic table info

```{r table1, message=FALSE}
knitr::kable(as.matrix(table(df$race)))
```

### better formatted table info

```{r table2, message=FALSE}
labs <- as.matrix(summary(df$num_lab_procedures))
labs <- data.frame(amt = rownames(labs),
                  freq = labs[,1],
                  row.names = NULL)
knitr::kable(labs)
```

Row 
-------------------------------------

### dynamic table info

```{r table3, message=FALSE}
# Only showing a portion of the table for example; limit this because will make the file larger
DT::datatable(df[1:100,1:5], 
              options = list(bPaginate = TRUE))
```

